clean up devcontainer

diff --git a/.devcontainer/docker/Dockerfile b/.devcontainer/docker/Dockerfile
--- a/.devcontainer/docker/Dockerfile
+++ b/.devcontainer/docker/Dockerfile
@@ -1,13 +1,19 @@
 FROM debian:bookworm-slim
 
 ARG user_id=1000
-ARG group_id=$user_id
-
+ARG group_id=${user_id}
 ARG usr=bensimmersdev
 ARG workspace_env_name=workspace
 
 
-RUN apt-get update && apt-get install -y \
+ENV DEBIAN_FRONTEND=noninteractive
+ENV LANG=en_US.UTF-8
+ENV LANGUAGE=en_US:en
+ENV LC_ALL=en_US.UTF-8
+ENV SHELL /bin/bash
+
+
+RUN apt-get update && apt-get install -y --no-install-recommends \
   bash \
   bash-completion \
   sudo \
@@ -38,59 +44,24 @@ RUN apt-get update && apt-get install -y \
   tmux \
   locales \
   neofetch \
-  && apt-get clean -y \
+  && apt-get clean \
   && rm -rf /var/lib/apt/lists/*
 
-# Optional packages for c development
-# ===================================
-# RUN apt-get update && \
-#   apt-get install -y libncurses5-dev libncursesw5-dev
+# Generate locales
+RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8
 
-# RUN apt-get update && \
-#   apt-get install -y \
-#   procps \
-#   sysstat \
-#   && apt-get clean -y \
-#   && rm -rf /var/lib/apt/lists/*
-# ===================================
-
-
-# Optional packages for TypeScript development
-# ===================================
-# RUN apt-get update && \
-#   apt-get install -y nodejs npm
-
-# RUN npm install -g typescript
-# ===================================
-
-# Optional packages for Python development
-# ===================================
-# RUN apt-get update && \
-#   apt-get install -y python3 python3-pip
-
-# RUN pip3 install --upgrade pip
-# ===================================
-
-RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
-  locale-gen en_US.UTF-8 && \
-  update-locale LANG=en_US.UTF-8
-
+# Create user and workspace
 RUN groupadd --gid ${group_id} ${usr} \
   && useradd --uid ${user_id} --gid ${group_id} -m ${usr} \
   && echo "${usr} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${usr} \
   && chmod 0440 /etc/sudoers.d/${usr} \
-  && chown -R ${user_id}:${group_id} /home/${usr}
-
-RUN mkdir -p /${workspace_env_name} && chown ${user_id}:${group_id} /${workspace_env_name}
+  && mkdir -p /${workspace_env_name} \
+  && chown -R ${user_id}:${group_id} /home/${usr} /${workspace_env_name}
 
 USER ${usr}
 WORKDIR /${workspace_env_name}
 
 RUN mkdir -p ~/bin ~/scripts
 
-ENV DEBIAN_FRONTEND=noninteractive
-ENV LANG=en_US.UTF-8
-ENV LANGUAGE=en_US:en
-ENV LC_ALL=en_US.UTF-8
 
-ENV SHELL /bin/bash
+# HEALTHCHECK CMD curl --fail http://localhost:YOUR_PORT || exit 1
